spring.application.name=ecom-app
server.port=8082
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test
spring.jpa.show-sql=true
# Save log output to a specific file name
logging.file.name=logs/application.log

# Set maximum size before a log file splits and rotates
logging.file.max-size=10MB

# Keep a maximum history of archived log files
logging.file.max-history=30